### ISSUE TITLE
关于client_router结构的疑问

### ISSUE THREAD

**Issue by wangxiyu191** [magicshui/qingcloud-go#1]
为什么要把router的model单独放到一个新的package里去？出于何种考虑？
能不能直接放在client_router.go里？好像这样比较符合golang的编程风格。

PS：最近在写一个青云的主机管理工具，主要是实例管理和IP管理这一块……打算在你的包的基础上扩充API，但是没太看懂结构………

**Comment by magicshui** [comment]
抱歉，这个是最早的版本，当时我就只需要这个功能，我稍后会做一个修改；
把业务逻辑全部剥离出来，放到单独的package中；

**Comment by magicshui** [comment]
新的结构参考：https://github.com/magicshui/leancloud

**Comment by magicshui** [comment]
已经剥离出来，最外面的Client只负责签名和发送请求，各个业务package的client来具体实现各自的业务；
另外由于青云的API太过于灵活，所以新的版本把数据转换成model的功能交给使用者自己来做；
